export const mcObjects = [
    "Acacia Button",
    "Acacia Door",
    "Acacia Fence",
    "Acacia Fence Gate",
    "Acacia Hanging Sign",
    "Acacia Leaves",
    "Acacia Log",
    "Acacia Planks",
    "Acacia Pressure Plate",
    "Acacia Sapling",
    "Acacia Sign",
    "Acacia Slab",
    "Acacia Stairs",
    "Acacia Trapdoor",
    "Acacia Wall Hanging Sign",
    "Acacia Wall Sign",
    "Acacia Wood",
    "Activator Rail",
    "Allium",
    "Amethyst Block",
    "Amethyst Cluster",
    "Ancient Debris",
    "Andesite",
    "Andesite Slab",
    "Andesite Stairs",
    "Andesite Wall",
    "Anvil",
    "Attached Melon Stem",
    "Attached Pumpkin Stem",
    "Azalea",
    "Azalea Leaves",
    "Azure Bluet",
    "Bamboo",
    "Bamboo Block",
    "Bamboo Button",
    "Bamboo Door",
    "Bamboo Fence",
    "Bamboo Fence Gate",
    "Bamboo Mosaic",
    "Bamboo Mosaic Slab",
    "Bamboo Mosaic Stairs",
    "Bamboo Planks",
    "Bamboo Pressure Plate",
    "Bamboo Sapling",
    "Bamboo Sign",
    "Bamboo Slab",
    "Bamboo Stairs",
    "Bamboo Trapdoor",
    "Bamboo Wall Hanging Sign",
    "Bamboo Wall Sign",
    "Barrel",
    "Basalt",
    "Beacon",
    "Bee Nest",
    "Beehive",
    "Beetroots",
    "Bell",
    "Big Dripleaf",
    "Big Dripleaf Stem",
    "Birch Button",
    "Birch Door",
    "Birch Fence",
    "Birch Fence Gate",
    "Birch Hanging Sign",
    "Birch Leaves",
    "Birch Log",
    "Birch Planks",
    "Birch Pressure Plate",
    "Birch Sapling",
    "Birch Sign",
    "Birch Slab",
    "Birch Stairs",
    "Birch Trapdoor",
    "Birch Wall Hanging Sign",
    "Birch Wall Sign",
    "Birch Wood",
    "Black Banner",
    "Black Bed",
    "Black Candle",
    "Black Candle Cake",
    "Black Carpet",
    "Black Concrete",
    "Black Concrete Powder",
    "Black Glazed Terracotta",
    "Black Stained Glass",
    "Black Stained Glass Pane",
    "Black Terracotta",
    "Black Wall Banner",
    "Black Wool",
    "Blackstone",
    "Blackstone Slab",
    "Blackstone Stairs",
    "Blackstone Wall",
    "Blast Furnace",
    "Blue Banner",
    "Blue Bed",
    "Blue Carpet",
    "Blue Concrete",
    "Blue Concrete Powder",
    "Blue Glazed Terracotta",
    "Blue Ice",
    "Blue Orchid",
    "Blue Stained Glass",
    "Blue Stained Glass Pane",
    "Blue Terracotta",
    "Blue Wall Banner",
    "Blue Wool",
    "Bone Block",
    "Bone Meal",
    "Bookshelf",
    "Brain Coral",
    "Brain Coral Block",
    "Brain Coral Fan",
    "Brain Coral Wall Fan",
    "Brewing Stand",
    "Brick Slab",
    "Brick Stairs",
    "Brick Wall",
    "Bricks",
    "Brown Bed",
    "Brown Carpet",
    "Brown Concrete",
    "Brown Concrete Powder",
    "Brown Glazed Terracotta",
    "Brown Mushroom",
    "Brown Mushroom Block",
    "Brown Stained Glass",
    "Brown Terracotta",
    "Brown Wall Banner",
    "Brown Wool",
    "Bubble Coral",
    "Bubble Coral Block",
    "Bubble Coral Fan",
    "Bubble Coral Wall Fan",
    "Budding Amethyst",
    "Cactus",
    "Cake",
    "Calcite",
    "Campfire",
    "Candle",
    "Carrots",
    "Cartography Table",
    "Carved Pumpkin",
    "Cauldron",
    "Cave Vines",
    "Cave Vines Plant",
    "Chain",
    "Cherry Door",
    "Cherry Fence",
    "Cherry Fence Gate",
    "Cherry Hanging Sign",
    "Cherry Leaves",
    "Cherry Log",
    "Cherry Planks",
    "Cherry Sapling",
    "Cherry Sign",
    "Cherry Slab",
    "Cherry Stairs",
    "Cherry Trapdoor",
    "Cherry Wall Hanging Sign",
    "Cherry Wall Sign",
    "Cherry Wood",
    "Chest",
    "Chipped Anvil",
    "Chiseled Bookshelf",
    "Chiseled Deepslate",
    "Chiseled Nether Bricks",
    "Chiseled Polished Blackstone",
    "Chiseled Quartz Block",
    "Chiseled Red Sandstone",
    "Chiseled Sandstone",
    "Chiseled Stone Bricks",
    "Clay",
    "Coal Block",
    "Coal Ore",
    "Coarse Dirt",
    "Cobbled Deepslate",
    "Cobbled Deepslate Slab",
    "Cobbled Deepslate Stairs",
    "Cobbled Deepslate Wall",
    "Cobblestone",
    "Cobblestone Slab",
    "Cobblestone Stairs",
    "Cobblestone Wall",
    "Cobweb",
    "Cocoa",
    "Comparator",
    "Composter",
    "Conduit",
    "Copper Block",
    "Copper Ore",
    "Cornflower",
    "Cracked Deepslate Bricks",
    "Cracked Deepslate Tiles",
    "Cracked Nether Bricks",
    "Cracked Polished Blackstone Bricks",
    "Cracked Stone Bricks",
    "Crafting Table",
    "Crimson Fence",
    "Crimson Fungus",
    "Crimson Hyphae",
    "Crimson Nylium",
    "Crimson Planks",
    "Crimson Roots",
    "Crimson Slab",
    "Crimson Stairs",
    "Crimson Stem",
    "Crimson Trapdoor",
    "Crying Obsidian",
    "Cut Copper",
    "Cut Copper Slab",
    "Cut Copper Stairs",
    "Cut Red Sandstone",
    "Cut Sandstone",
    "Cut Sandstone Slab",
    "Cyan Bed",
    "Cyan Candle",
    "Cyan Carpet",
    "Cyan Glazed Terracotta",
    "Cyan Stained Glass",
    "Cyan Stained Glass Pane",
    "Cyan Terracotta",
    "Cyan Wall Banner",
    "Cyan Wool",
    "Damaged Anvil",
    "Dandelion",
    "Dark Oak Button",
    "Dark Oak Door",
    "Dark Oak Fence",
    "Dark Oak Fence Gate",
    "Dark Oak Hanging Sign",
    "Dark Oak Leaves",
    "Dark Oak Log",
    "Dark Oak Planks",
    "Dark Oak Pressure Plate",
    "Dark Oak Sapling",
    "Dark Oak Sign",
    "Dark Oak Slab",
    "Dark Oak Stairs",
    "Dark Oak Trapdoor",
    "Dark Oak Wall Hanging Sign",
    "Dark Oak Wall Sign",
    "Dark Oak Wood",
    "Dark Prismarine",
    "Dark Prismarine Slab",
    "Dark Prismarine Stairs",
    "Dead Brain Coral",
    "Dead Brain Coral Block",
    "Dead Brain Coral Fan",
    "Dead Brain Coral Wall Fan",
    "Dead Bubble Coral",
    "Dead Bubble Coral Block",
    "Dead Bubble Coral Wall Fan",
    "Dead Bush",
    "Dead Fire Coral",
    "Dead Fire Coral Block",
    "Dead Fire Coral Fan",
    "Dead Fire Coral Wall Fan",
    "Dead Horn Coral",
    "Dead Horn Coral Block",
    "Dead Horn Coral Fan",
    "Dead Horn Coral Wall Fan",
    "Dead Tube Coral",
    "Dead Tube Coral Fan",
    "Dead Tube Coral Wall Fan",
    "Decorated Pot",
    "Deepslate",
    "Deepslate Brick Slab",
    "Deepslate Brick Stairs",
    "Deepslate Brick Wall",
    "Deepslate Bricks",
    "Deepslate Coal Ore",
    "Deepslate Copper Ore",
    "Deepslate Diamond Ore",
    "Deepslate Emerald Ore",
    "Deepslate Gold Ore",
    "Deepslate Iron Ore",
    "Deepslate Lapis Ore",
    "Deepslate Redstone Ore",
    "Deepslate Tile Slab",
    "Deepslate Tile Stairs",
    "Deepslate Tile Wall",
    "Deepslate Tiles",
    "Detector Rail",
    "Diamond Block",
    "Diamond Ore",
    "Diorite",
    "Diorite Slab",
    "Diorite Stairs",
    "Diorite Wall",
    "Dirt",
    "Dirt Path",
    "Dispenser",
    "Dripstone Block",
    "Dropper",
    "Emerald Block",
    "Emerald Ore",
    "Enchanted Book",
    "Enchanting Table",
    "End Rod",
    "Ender Chest",
    "Exposed Copper",
    "Exposed Cut Copper Slab",
    "Exposed Cut Copper Stairs",
    "Farmland",
    "Fern",
    "Fire",
    "Fire Coral",
    "Fire Coral Block",
    "Fire Coral Fan",
    "Fire Coral Wall Fan",
    "Fletching Table",
    "Flower Pot",
    "Flowering Azalea",
    "Flowering Azalea Leaves",
    "Frosted Ice",
    "Furnace",
    "Gilded Blackstone",
    "Glass",
    "Glass Pane",
    "Glow Lichen",
    "Glowstone",
    "Gold Block",
    "Gold Ore",
    "Granite",
    "Granite Slab",
    "Granite Stairs",
    "Granite Wall",
    "Grass",
    "Grass Block",
    "Gravel",
    "Gray Banner",
    "Gray Bed",
    "Gray Candle",
    "Gray Carpet",
    "Gray Concrete",
    "Gray Concrete Powder",
    "Gray Glazed Terracotta",
    "Gray Stained Glass",
    "Gray Stained Glass Pane",
    "Gray Terracotta",
    "Gray Wall Banner",
    "Gray Wool",
    "Green Bed",
    "Green Candle",
    "Green Carpet",
    "Green Concrete",
    "Green Concrete Powder",
    "Green Stained Glass",
    "Green Stained Glass Pane",
    "Green Terracotta",
    "Green Wall Banner",
    "Green Wool",
    "Grindstone",
    "Hanging Roots",
    "Hay Block",
    "Heavy Weighted Pressure Plate",
    "Honey Block",
    "Honeycomb Block",
    "Hopper",
    "Horn Coral",
    "Horn Coral Block",
    "Horn Coral Fan",
    "Horn Coral Wall Fan",
    "Ice",
    "Infested Deepslate",
    "Infested Stone",
    "Infested Stone Bricks",
    "Iron Bars",
    "Iron Block",
    "Iron Door",
    "Iron Ore",
    "Iron Trapdoor",
    "Jack O Lantern",
    "Jukebox",
    "Jungle Button",
    "Jungle Door",
    "Jungle Fence",
    "Jungle Fence Gate",
    "Jungle Leaves",
    "Jungle Log",
    "Jungle Planks",
    "Jungle Sapling",
    "Jungle Sign",
    "Jungle Slab",
    "Jungle Stairs",
    "Jungle Trapdoor",
    "Jungle Wall Sign",
    "Jungle Wood",
    "Kelp",
    "Kelp Plant",
    "Ladder",
    "Lantern",
    "Lapis Block",
    "Lapis Ore",
    "Large Amethyst Bud",
    "Large Fern",
    "Lava Cauldron",
    "Lectern",
    "Lever",
    "Light Blue Candle",
    "Light Blue Carpet",
    "Light Blue Concrete",
    "Light Blue Concrete Powder",
    "Light Blue Stained Glass",
    "Light Blue Stained Glass Pane",
    "Light Blue Terracotta",
    "Light Blue Wall Banner",
    "Light Blue Wool",
    "Light Gray Bed",
    "Light Gray Carpet",
    "Light Gray Concrete",
    "Light Gray Concrete Powder",
    "Light Gray Glazed Terracotta",
    "Light Gray Stained Glass",
    "Light Gray Stained Glass Pane",
    "Light Gray Terracotta",
    "Light Gray Wall Banner",
    "Light Gray Wool",
    "Light Weighted Pressure Plate",
    "Lightning Rod",
    "Lilac",
    "Lily Of The Valley",
    "Lily Pad",
    "Lime Bed",
    "Lime Candle",
    "Lime Carpet",
    "Lime Concrete",
    "Lime Concrete Powder",
    "Lime Glazed Terracotta",
    "Lime Stained Glass",
    "Lime Terracotta",
    "Lime Wall Banner",
    "Lime Wool",
    "Lodestone",
    "Loom",
    "Magenta Bed",
    "Magenta Stained Glass",
    "Magenta Stained Glass Pane",
    "Magenta Terracotta",
    "Magenta Wool",
    "Magma Block",
    "Mangrove Door",
    "Mangrove Fence",
    "Mangrove Fence Gate",
    "Mangrove Leaves",
    "Mangrove Log",
    "Mangrove Planks",
    "Mangrove Propagule",
    "Mangrove Roots",
    "Mangrove Slab",
    "Mangrove Stairs",
    "Mangrove Trapdoor",
    "Mangrove Wall Sign",
    "Mangrove Wood",
    "Medium Amethyst Bud",
    "Melon",
    "Melon Stem",
    "Moss Block",
    "Moss Carpet",
    "Mossy Cobblestone",
    "Mossy Cobblestone Slab",
    "Mossy Cobblestone Stairs",
    "Mossy Cobblestone Wall",
    "Mossy Stone Brick Slab",
    "Mossy Stone Brick Stairs",
    "Mossy Stone Brick Wall",
    "Mossy Stone Bricks",
    "Mud",
    "Mud Brick Slab",
    "Mud Brick Stairs",
    "Mud Brick Wall",
    "Mud Bricks",
    "Muddy Mangrove Roots",
    "Mushroom Stem",
    "Nether Brick Fence",
    "Nether Brick Slab",
    "Nether Brick Stairs",
    "Nether Brick Wall",
    "Nether Bricks",
    "Nether Gold Ore",
    "Nether Quartz Ore",
    "Nether Sprouts",
    "Nether Wart",
    "Nether Wart Block",
    "Netherrack",
    "Note Block",
    "Oak Button",
    "Oak Door",
    "Oak Fence",
    "Oak Fence Gate",
    "Oak Hanging Sign",
    "Oak Leaves",
    "Oak Log",
    "Oak Planks",
    "Oak Pressure Plate",
    "Oak Sapling",
    "Oak Sign",
    "Oak Slab",
    "Oak Stairs",
    "Oak Trapdoor",
    "Oak Wall Hanging Sign",
    "Oak Wall Sign",
    "Oak Wood",
    "Observer",
    "Obsidian",
    "Ochre Froglight",
    "Orange Bed",
    "Orange Candle",
    "Orange Carpet",
    "Orange Concrete",
    "Orange Glazed Terracotta",
    "Orange Stained Glass",
    "Orange Stained Glass Pane",
    "Orange Terracotta",
    "Orange Tulip",
    "Orange Wool",
    "Oxeye Daisy",
    "Oxidized Copper",
    "Oxidized Cut Copper",
    "Oxidized Cut Copper Slab",
    "Oxidized Cut Copper Stairs",
    "Packed Ice",
    "Packed Mud",
    "Pearlescent Froglight",
    "Peony",
    "Pink Bed",
    "Pink Carpet",
    "Pink Concrete",
    "Pink Petals",
    "Pink Stained Glass",
    "Pink Stained Glass Pane",
    "Pink Terracotta",
    "Pink Tulip",
    "Pink Wall Banner",
    "Pink Wool",
    "Piston",
    "Piston Head",
    "Pitcher Crop",
    "Pitcher Plant",
    "Player Head",
    "Player Wall Head",
    "Podzol",
    "Pointed Dripstone",
    "Polished Andesite",
    "Polished Andesite Slab",
    "Polished Andesite Stairs",
    "Polished Basalt",
    "Polished Blackstone",
    "Polished Blackstone Brick Slab",
    "Polished Blackstone Brick Stairs",
    "Polished Blackstone Brick Wall",
    "Polished Blackstone Bricks",
    "Polished Blackstone Button",
    "Polished Blackstone Pressure Plate",
    "Polished Blackstone Slab",
    "Polished Blackstone Stairs",
    "Polished Blackstone Wall",
    "Polished Deepslate",
    "Polished Deepslate Slab",
    "Polished Deepslate Stairs",
    "Polished Deepslate Wall",
    "Polished Diorite",
    "Polished Diorite Slab",
    "Polished Diorite Stairs",
    "Polished Granite",
    "Polished Granite Slab",
    "Polished Granite Stairs",
    "Poppy",
    "Potatoes",
    "Potted Acacia Sapling",
    "Potted Allium",
    "Potted Azalea Bush",
    "Potted Bamboo",
    "Potted Birch Sapling",
    "Potted Blue Orchid",
    "Potted Cactus",
    "Potted Cherry Sapling",
    "Potted Crimson Fungus",
    "Potted Dandelion",
    "Potted Dark Oak Sapling",
    "Potted Dead Bush",
    "Potted Fern",
    "Potted Flowering Azalea Bush",
    "Potted Jungle Sapling",
    "Potted Oak Sapling",
    "Potted Orange Tulip",
    "Potted Red Mushroom",
    "Potted Spruce Sapling",
    "Potted Torchflower",
    "Potted White Tulip",
    "Potted Wither Rose",
    "Powder Snow",
    "Powder Snow Cauldron",
    "Powered Rail",
    "Prismarine",
    "Prismarine Brick Slab",
    "Prismarine Brick Stairs",
    "Prismarine Bricks",
    "Prismarine Slab",
    "Prismarine Stairs",
    "Prismarine Wall",
    "Pumpkin",
    "Pumpkin Stem",
    "Purple Bed",
    "Purple Glazed Terracotta",
    "Purple Stained Glass",
    "Purple Stained Glass Pane",
    "Purple Terracotta",
    "Purple Wool",
    "Quartz Block",
    "Quartz Bricks",
    "Quartz Pillar",
    "Quartz Slab",
    "Quartz Stairs",
    "Rail",
    "Raw Copper Block",
    "Raw Gold Block",
    "Raw Iron Block",
    "Red Bed",
    "Red Candle",
    "Red Carpet",
    "Red Concrete",
    "Red Concrete Powder",
    "Red Glazed Terracotta",
    "Red Mushroom",
    "Red Mushroom Block",
    "Red Nether Brick Slab",
    "Red Nether Brick Stairs",
    "Red Nether Brick Wall",
    "Red Nether Bricks",
    "Red Sand",
    "Red Sandstone",
    "Red Sandstone Stairs",
    "Red Stained Glass",
    "Red Stained Glass Pane",
    "Red Terracotta",
    "Red Tulip",
    "Red Wool",
    "Redstone Block",
    "Redstone Lamp",
    "Redstone Ore",
    "Redstone Torch",
    "Redstone Wall Torch",
    "Redstone Wire",
    "Repeater",
    "Respawn Anchor",
    "Rooted Dirt",
    "Rose Bush",
    "Sand",
    "Sandstone",
    "Sandstone Slab",
    "Sandstone Stairs",
    "Sandstone Wall",
    "Scaffolding",
    "Sculk",
    "Sculk Catalyst",
    "Sculk Sensor",
    "Sculk Shrieker",
    "Sculk Vein",
    "Sea Lantern",
    "Sea Pickle",
    "Seagrass",
    "Shroomlight",
    "Skeleton Skull",
    "Slime Block",
    "Small Amethyst Bud",
    "Small Dripleaf",
    "Smithing Table",
    "Smoker",
    "Smooth Basalt",
    "Smooth Quartz",
    "Smooth Quartz Slab",
    "Smooth Quartz Stairs",
    "Smooth Red Sandstone",
    "Smooth Sandstone",
    "Smooth Sandstone Slab",
    "Smooth Sandstone Stairs",
    "Smooth Stone",
    "Smooth Stone Slab",
    "Sniffer Egg",
    "Snow",
    "Snow Block",
    "Soul Campfire",
    "Soul Fire",
    "Soul Lantern",
    "Soul Sand",
    "Soul Soil",
    "Soul Torch",
    "Spawner",
    "Sponge",
    "Spore Blossom",
    "Spruce Button",
    "Spruce Door",
    "Spruce Fence",
    "Spruce Fence Gate",
    "Spruce Hanging Sign",
    "Spruce Leaves",
    "Spruce Log",
    "Spruce Planks",
    "Spruce Pressure Plate",
    "Spruce Sapling",
    "Spruce Sign",
    "Spruce Slab",
    "Spruce Stairs",
    "Spruce Trapdoor",
    "Spruce Wall Hanging Sign",
    "Spruce Wall Sign",
    "Spruce Wood",
    "Sticky Piston",
    "Stone",
    "Stone Brick Slab",
    "Stone Brick Stairs",
    "Stone Brick Wall",
    "Stone Bricks",
    "Stone Button",
    "Stone Pressure Plate",
    "Stone Slab",
    "Stone Stairs",
    "Stonecutter",
    "Stripped Acacia Log",
    "Stripped Acacia Wood",
    "Stripped Bamboo Block",
    "Stripped Birch Log",
    "Stripped Birch Wood",
    "Stripped Cherry Log",
    "Stripped Cherry Wood",
    "Stripped Crimson Stem",
    "Stripped Dark Oak Log",
    "Stripped Dark Oak Wood",
    "Stripped Jungle Log",
    "Stripped Jungle Wood",
    "Stripped Mangrove Log",
    "Stripped Mangrove Wood",
    "Stripped Oak Log",
    "Stripped Oak Wood",
    "Stripped Spruce Log",
    "Stripped Spruce Wood",
    "Stripped Warped Hyphae",
    "Stripped Warped Stem",
    "Sugar Cane",
    "Sunflower",
    "Suspicious Gravel",
    "Suspicious Sand",
    "Sweet Berry Bush",
    "Tall Grass",
    "Tall Seagrass",
    "Target",
    "Terracotta",
    "Tinted Glass",
    "Tnt",
    "Torch",
    "Torchflower",
    "Trapped Chest",
    "Tripwire",
    "Tripwire Hook",
    "Tube Coral",
    "Tube Coral Block",
    "Tube Coral Fan",
    "Tube Coral Wall Fan",
    "Tuff",
    "Turtle Egg",
    "Twisting Vines",
    "Twisting Vines Plant",
    "Verdant Froglight",
    "Vine",
    "Wall Torch",
    "Warped Button",
    "Warped Door",
    "Warped Fence",
    "Warped Fence Gate",
    "Warped Fungus",
    "Warped Hyphae",
    "Warped Nylium",
    "Warped Planks",
    "Warped Roots",
    "Warped Slab",
    "Warped Stem",
    "Warped Trapdoor",
    "Warped Wart Block",
    "Water Cauldron",
    "Waxed Copper Block",
    "Waxed Cut Copper",
    "Waxed Cut Copper Slab",
    "Waxed Cut Copper Stairs",
    "Waxed Exposed Copper",
    "Waxed Exposed Cut Copper",
    "Waxed Exposed Cut Copper Slab",
    "Waxed Oxidized Cut Copper Stairs",
    "Waxed Weathered Copper",
    "Waxed Weathered Cut Copper",
    "Waxed Weathered Cut Copper Slab",
    "Waxed Weathered Cut Copper Stairs",
    "Weathered Copper",
    "Weathered Cut Copper",
    "Weathered Cut Copper Stairs",
    "Weeping Vines",
    "Weeping Vines Plant",
    "Wet Sponge",
    "Wheat",
    "White Banner",
    "White Bed",
    "White Candle",
    "White Carpet",
    "White Concrete",
    "White Concrete Powder",
    "White Glazed Terracotta",
    "White Stained Glass",
    "White Stained Glass Pane",
    "White Terracotta",
    "White Tulip",
    "White Wall Banner",
    "White Wool",
    "Wither Rose",
    "Wither Skeleton Skull",
    "Wither Skeleton Wall Skull",
    "Yellow Banner",
    "Yellow Bed",
    "Yellow Candle",
    "Yellow Carpet",
    "Yellow Concrete",
    "Yellow Glazed Terracotta",
    "Yellow Stained Glass",
    "Yellow Stained Glass Pane",
    "Yellow Terracotta",
    "Yellow Wall Banner",
    "Yellow Wool",
    "Diamond Sword",
    "Diamond Pickaxe",
    "Diamond Shovel",
    "Diamond Axe",
    "Diamond Hoe",
    "Iron Sword",
    "Iron Pickaxe",
    "Iron Shovel",
    "Iron Axe",
    "Iron Hoe",
    "Golden Sword",
    "Golden Pickaxe",
    "Golden Shovel",
    "Golden Axe",
    "Golden Hoe",
    "Stone Sword",
    "Stone Pickaxe",
    "Stone Shovel",
    "Stone Axe",
    "Stone Hoe",
    "Wooden Sword",
    "Wooden Pickaxe",
    "Wooden Shovel",
    "Wooden Axe",
    "Wooden Hoe",
    "Bow",
    "Arrow",
    "Diamond Armor Set",
    "Iron Armor Set",
    "Golden Armor Set",
    "Chainmail Armor Set",
    "Leather Armor Set",
    "Shield",
    "Elytra",
    "Enchanting Table",
    "Anvil",
    "Furnace",
    "Crafting Table",
    "Bed",
    "Ender Chest",
    "Chest",
    "Ender Pearl",
    "Blaze Rod",
    "Ghast Tear",
    "Ender Eye",
    "Nether Star",
    "Nether Wart",
    "Blaze Powder",
    "Magma Cream",
    "Glistering Melon",
    "Rabbit Foot",
    "Rabbit Hide",
    "Rabbit Stew",
    "Potion of Healing",
    "Potion of Fire Resistance",
    "Potion of Strength",
    "Potion of Swiftness",
    "Potion of Invisibility",
    "Splash Potion",
    "Lingering Potion",
    "Golden Apple",
    "Golden Carrot",
    "Cooked Beef",
    "Cooked Porkchop",
    "Baked Potato",
    "Bread",
    "Cake",
    "Cookie",
    "Melon Slice",
    "Pumpkin Pie",
    "Sugar",
    "Blaze Powder",
    "Ender Pearl",
    "Diamond",
    "Emerald",
    "Iron Ingot",
    "Gold Ingot",
    "Redstone",
    "Lapis Lazuli",
    "Coal",
    "Glass",
    "Book",
    "Bookshelf",
    "Paper",
    "Map",
    "Compass",
    "Clock",
    "Ender Pearl",
    "Cooked Mutton"
]